# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build Energy CLI
      run: |
        cd ./cmd/energy
        go install
        energy
        energy cli -v

    - name: Windows Test CGO ENABLED
      if: matrix.os == 'windows-2019'
      run: |
        set CGO_ENABLED=1
        go env

    - name: Test
      run: |
        go mod tidy
        go test -v -coverprofile="cover.out" -covermode=atomic ./...
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
       token: ${{ secrets.CODECOV_TOKEN }}
       file: "cover.out"
       flags: unittests
       verbose: true
